SELECT * FROM public.shopping_data

--Q.1.WHAT IS THE TOTAL REVENUE GENERATED BY MALE V/S FEMALE CUSTOMER?
SELECT "Gender", SUM("Purchase Amount (USD)") as revenue
FROM shopping_data
GROUP BY "Gender";


--Q.2 WHICH CUSTOMER USED A DISCOUNT BUT STILL SPENT MORE THEN THE AVERAGE PURVHASE AMOUNT?
SELECT "Customer ID", "Purchase Amount (USD)"
FROM shopping_data
WHERE "Discount Applied" = 'Yes' 
AND "Purchase Amount (USD)" >= (SELECT AVG("Purchase Amount (USD)") FROM shopping_data);

--Q.3 WHICH ARE THE TOP 5 PRODUCTS WITH THE HIGHEST AVERAGE REVIEW RATING?
SELECT "Item Purchased", AVG("Review Rating") as "Average Product Rating"
FROM shopping_data
GROUP BY "Item Purchased"
ORDER BY "Average Product Rating" DESC
LIMIT 5;



SELECT "Item Purchased", ROUND(AVG("Review Rating"::numeric), 2) as "Average Product Rating"
FROM shopping_data
GROUP BY "Item Purchased"
ORDER BY "Average Product Rating" DESC
LIMIT 5;

-- Q.4 Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT "Shipping Type", ROUND(AVG("Purchase Amount (USD)"::numeric), 2) as "Average Purchase"
FROM shopping_data
WHERE "Shipping Type" IN ('Standard', 'Express')
GROUP BY "Shipping Type";


--Q.5 DO SUBSCRIBED CUSTOMERS SPEND MORE?COMPARE AVERAGE SPEND AND TOTAL REVENUE BETWEEN SUBSCRIBED AND NON SUBSCRIBED?

SELECT 
    "Subscription Status", 
    COUNT("Customer ID") as total_customers, 
    ROUND(AVG("Purchase Amount (USD)"::numeric), 2) as avg_spend, 
    ROUND(SUM("Purchase Amount (USD)"::numeric), 2) as total_revenue
FROM shopping_data
GROUP BY "Subscription Status"
ORDER BY total_revenue DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
    "Item Purchased", 
    ROUND((SUM(CASE WHEN "Discount Applied" = 'Yes' THEN 1 ELSE 0 END)::numeric / COUNT(*)) * 100, 2) as discount_rate
FROM shopping_data
GROUP BY "Item Purchased"
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers based on their total number of previous purchases
WITH customer_type AS (
    SELECT 
        "Customer ID", 
        "Previous Purchases",
        CASE 
            WHEN "Previous Purchases" = 1 THEN 'New'
            WHEN "Previous Purchases" BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM shopping_data
)
SELECT customer_segment, COUNT(*) as "Number of Customers"
FROM customer_type
GROUP BY customer_segment;


-- Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT 
        "Category", 
        "Item Purchased", 
        COUNT("Customer ID") as total_orders,
        ROW_NUMBER() OVER(
            PARTITION BY "Category" 
            ORDER BY COUNT("Customer ID") DESC
        ) as item_rank
    FROM shopping_data
    GROUP BY "Category", "Item Purchased"
)
SELECT item_rank, "Category", "Item Purchased", total_orders
FROM item_counts
WHERE item_rank <= 3;	


-- Q9. Are repeat buyers (more than 5 purchases) also likely to subscribe?
SELECT 
    "Subscription Status", 
    COUNT("Customer ID") as repeat_buyers
FROM shopping_data
WHERE "Previous Purchases" > 5
GROUP BY "Subscription Status";

-- Q10. What is the revenue contribution of each age group?
SELECT 
    CASE 
        WHEN "Age" BETWEEN 18 AND 30 THEN '18-30'
        WHEN "Age" BETWEEN 31 AND 50 THEN '31-50'
        ELSE '51+' 
    END AS age_group,
    SUM("Purchase Amount (USD)") as total_revenue
FROM shopping_data
GROUP BY age_group
ORDER BY total_revenue DESC;


-- Q10. What is the revenue contribution of each age group?
SELECT 
    CASE 
        WHEN "Age" BETWEEN 18 AND 30 THEN 'Young Adult'
        WHEN "Age" BETWEEN 31 AND 50 THEN 'Middle-aged'
        WHEN "Age" BETWEEN 51 AND 65 THEN 'Adult'
        ELSE 'Senior' 
    END AS age_group_category,
    SUM("Purchase Amount (USD)") as total_revenue
FROM shopping_data
GROUP BY age_group_category
ORDER BY total_revenue DESC;